export const mockContacts = [
  {
    id: 1,
    name: "Lea",
    lastMessage: "Hi, i am jo...",
    date: "22/10/23",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    status: "online",
    messageStatus: { type: "sent", value: "" },
  },
  {
    id: 2,
    name: "Jony Lynetin",
    lastMessage: "Hello 👋",
    date: "30/11/23",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    status: "online",
    messageStatus: { type: "unread", value: 8 },
  },
  {
    id: 3,
    name: "Sufiya Elija",
    lastMessage: "I need job, pleas...",
    date: "15/06/23",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    status: "away",
    messageStatus: { type: "sending", value: "Sending" },
  },
  {
    id: 4,
    name: "Pabelo Mukrani",
    lastMessage: "Hi, i am josephin...",
    date: "Just Now",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    status: "offline",
    messageStatus: { type: "failed", value: "Failed" },
  },
  {
    id: 5,
    name: "Alicia Keys",
    lastMessage: "Let's catch up later.",
    date: "12/12/23",
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    status: "online",
    messageStatus: { type: "read", value: "" },
  },
  {
    id: 6,
    name: "Michael Scott",
    lastMessage: "That's what she said!",
    date: "11/11/23",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    status: "offline",
    messageStatus: { type: "unread", value: 2 },
  },
  {
    id: 7,
    name: "Rachel Green",
    lastMessage: "Could I BE any more excited?",
    date: "10/10/23",
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
    status: "away",
    messageStatus: { type: "sent", value: "" },
  },
  {
    id: 8,
    name: "David Beckham",
    lastMessage: "Game on this weekend?",
    date: "09/09/23",
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
    status: "online",
    messageStatus: { type: "read", value: "" },
  },
];

export const mockConversations = {
  1: [
    // Messages for Lea (ID 1)
    {
      id: 101,
      sender: "them",
      type: "text",
      text: "You understand ❤️",
      time: "01:45 AM",
    },
    {
      id: 102,
      sender: "me",
      type: "file",
      fileName: "Smitten Shah 01.pdf",
      fileInfo: "1 Page | 250 kb",
      time: "01:46 AM",
    },
    {
      id: 103,
      sender: "them",
      type: "image",
      text: "You understand 😄",
      images: [
        "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=400&h=400&fit=crop",
        "https://images.unsplash.com/photo-1499244571948-7ccddb3583ea?w=400&h=400&fit=crop",
        "https://images.unsplash.com/photo-1523437113738-bbd3cc89fb19?w=400&h=400&fit=crop",
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&h=400&fit=crop",
        "https://images.unsplash.com/photo-1511300636412-01634217bfde?w=400&h=400&fit=crop",
      ],
      time: "01:45 AM",
    },
  ],
  2: [
    // Messages for Jony Lynetin (ID 2)
    {
      id: 201,
      sender: "them",
      type: "text",
      text: "Hey, how are you?",
      time: "Yesterday",
    },
    {
      id: 202,
      sender: "me",
      type: "text",
      text: "Doing great, thanks! How about you?",
      time: "Yesterday",
    },
  ],
};
